In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_excel('./knn.xlsx')
df

A1  A2  A3  A4 target
0    1   1   4   4      B
1    3   0   5   1      C
2    1   0   0   5      B
3    2   5   0   1      C
4    2   1   1   2      D
5    4   3   3   3      A
6    0   1   0   2      D
7    3   4   4   4      A
8    4   1   4   3      D
9    3   1   3   3      A
10   2   1   2   1      A
11   3   2   3   4      D
12   1   5   3   1      B
13   4   2   0   1      C
14   1   1   4   3      B
15   3   0   0   0      C

In [26]:
Xtrain = df.iloc[:8,:-1]
Xtest = df.iloc[8:,:-1]

In [27]:
Xtest

A1  A2  A3  A4
8    4   1   4   3
9    3   1   3   3
10   2   1   2   1
11   3   2   3   4
12   1   5   3   1
13   4   2   0   1
14   1   1   4   3
15   3   0   0   0

In [19]:
#Manhattan L1-norm
for index, xi in Xtest.iterrows():
     #print(np.sum(abs(X-xi), axis=1))
     print('ID : ',index)
     print(np.sum(abs(Xtrain-xi), axis=1))

ID :  3
0    12
1    11
2    10
dtype: int64
ID :  4
0    6
1    7
2    6
dtype: int64
ID :  5
0     7
1     8
2    11
dtype: int64
ID :  6
0     7
1    10
2     5
dtype: int64
ID :  7
0     5
1     8
2    11
dtype: int64
ID :  8
0     4
1     5
2    10
dtype: int64
ID :  9
0    4
1    5
2    8
dtype: int64
ID :  10
0    6
1    5
2    8
dtype: int64
ID :  11
0    4
1    7
2    8
dtype: int64
ID :  12
0     8
1     9
2    12
dtype: int64
ID :  13
0    11
1     8
2     9
dtype: int64
ID :  14
0    1
1    6
2    7
dtype: int64
ID :  15
0    11
1     6
2     7
dtype: int64


In [20]:
#euclidean
for index, xi in Xtest.iterrows():
     print('ID : ',index)
     print()

ID :  3
0    6.480741
1    7.141428
2    6.480741
dtype: float64
ID :  4
0    3.741657
1    4.358899
2    3.464102
dtype: float64
ID :  5
0    3.872983
1    4.242641
2    5.567764
dtype: float64
ID :  6
0    4.582576
1    6.000000
2    3.316625
dtype: float64
ID :  7
0    3.605551
1    5.099020
2    6.082763
dtype: float64
ID :  8
0    3.162278
1    2.645751
2    5.477226
dtype: float64
ID :  9
0    2.449490
1    3.000000
2    4.242641
dtype: float64
ID :  10
0    3.741657
1    3.316625
2    4.690416
dtype: float64
ID :  11
0    2.449490
1    4.123106
2    4.242641
dtype: float64
ID :  12
0    5.099020
1    5.744563
2    7.071068
dtype: float64
ID :  13
0    5.916080
1    5.477226
2    5.385165
dtype: float64
ID :  14
0    1.000000
1    3.162278
2    4.582576
dtype: float64
ID :  15
0    6.082763
1    5.099020
2    5.385165
dtype: float64


In [28]:
#squared euclidean
for index, xi in Xtest.iterrows():
     print('ID : ',index)
     print(np.sum(abs(Xtrain-xi)**2, axis=1))

ID :  8
0    10
1     7
2    30
3    40
4    14
5     5
6    33
7    11
dtype: int64
ID :  9
0     6
1     9
2    18
3    30
4     6
5     5
6    19
7    11
dtype: int64
ID :  10
0    14
1    11
2    22
3    20
4     2
5    13
6     9
7    23
dtype: int64
ID :  11
0     6
1    17
2    18
3    28
4    10
5     3
6    23
7     5
dtype: int64
ID :  12
0    26
1    33
2    50
3    10
4    22
5    17
6    27
7    15
dtype: int64
ID :  13
0    35
1    30
2    29
3    13
4     7
5    14
6    18
7    30
dtype: int64
ID :  14
0     1
1    10
2    21
3    37
4    11
5    14
6    18
7    14
dtype: int64
ID :  15
0    37
1    26
2    29
3    27
4     7
5    28
6    14
7    48
dtype: int64


In [22]:
#Uniform/Supremum/Chebyshev/Infinity L∞-norm
for index, xi in Xtest.iterrows():
     print('ID : ',index)
     print(np.max(abs(Xtrain-xi), axis=1))


ID :  3
0    4
1    5
2    5
dtype: int64
ID :  4
0    3
1    4
2    3
dtype: int64
ID :  5
0    3
1    3
2    3
dtype: int64
ID :  6
0    4
1    5
2    3
dtype: int64
ID :  7
0    3
1    4
2    4
dtype: int64
ID :  8
0    3
1    2
2    4
dtype: int64
ID :  9
0    2
1    2
2    3
dtype: int64
ID :  10
0    3
1    3
2    4
dtype: int64
ID :  11
0    2
1    3
2    3
dtype: int64
ID :  12
0    4
1    5
2    5
dtype: int64
ID :  13
0    4
1    5
2    4
dtype: int64
ID :  14
0    1
1    2
2    4
dtype: int64
ID :  15
0    4
1    5
2    5
dtype: int64


In [23]:
#Lp-norm
p = 3/4
for index, xi in Xtest.iterrows():
     print('ID : ',index)
     print(np.power(np.sum(abs(Xtrain-xi)**p, axis=1),(1/p)))


ID :  3
0    18.544464
1    15.171885
2    13.831335
dtype: float64
ID :  4
0     8.461759
1    10.489026
2     9.193012
dtype: float64
ID :  5
0    10.809061
1    12.488025
2    17.402333
dtype: float64
ID :  6
0     9.732519
1    15.003194
2     6.947976
dtype: float64
ID :  7
0     6.267826
1    11.165010
2    16.909371
dtype: float64
ID :  8
0     4.872420
1     7.832185
2    15.441743
dtype: float64
ID :  9
0     5.685201
1     7.130577
2    12.488025
dtype: float64
ID :  10
0     8.461759
1     6.947976
2    12.156099
dtype: float64
ID :  11
0     5.685201
1    10.046688
2    12.488025
dtype: float64
ID :  12
0    11.165010
1    12.649185
2    17.215555
dtype: float64
ID :  13
0    17.041428
1    10.964536
2    12.856904
dtype: float64
ID :  14
0    1.000000
1    9.388732
2    9.732519
dtype: float64
ID :  15
0    16.909371
1     7.087286
2     8.608055
dtype: float64


LSH

In [33]:
code = [[5, 5, 1,-1],
        [4, 4, 5,5],
        [3, -2, 5,1]]
code = np.array(code)
df2 = pd.DataFrame(df.iloc[:,-1])

In [34]:
df2

target
0       B
1       C
2       B
3       C
4       D
5       A
6       D
7       A
8       D
9       A
10      A
11      D
12      B
13      C
14      B
15      C

In [35]:

for index,c in enumerate(code):
     print('---',c)
     print(np.dot(df.iloc[:,:-1],c))
     # h = np.where(np.dot(df.iloc[:,:-1],c)>=0,1,0)
     # df_temp = pd.DataFrame({'c'+str(index): h.tolist()})
     # df2 = df2.join(df_temp)


--- [ 5  5  1 -1]
[10 19  0 34 14 35  3 35 26 20 16 24 32 29 11 15]
--- [4 4 5 5]
[48 42 29 33 27 58 14 68 55 46 27 55 44 29 43 12]
--- [ 3 -2  5  1]
[25 35  8 -3 11 24  0 25 33 25 15 24  9  9 24  9]
